/** Public surface of the workspace feature — import from here, not from subpaths. */
export { NoteEditor } from './components/editor/NoteEditor'
export { RevertAllButton } from './components/sync/RevertAllButton'
export { SyncButton } from './components/sync/SyncButton'
export { SyncFab } from './components/sync/SyncFab'
export { TreeView } from './components/tree/TreeView'
export { useExpandedIds } from './hooks/use-expanded-ids'
export { useNote } from './hooks/use-note'
export { useNotePath } from './hooks/use-note-path'
export { useWorkspace } from './hooks/use-workspace'
export { WorkspaceProvider } from './store/WorkspaceProvider'
export { SyncProvider } from './sync/SyncProvider'
export { useSync } from './sync/sync-context'
export { DEFAULT_BRANCH } from './github/github-config'
export type { GitHubConfig } from './github/github-config'
export { isFolder, isNote } from './types'
export type { FolderItem, NoteItem, WorkspaceItem } from './types'
